stages:
  prepare:
    cmd: python scripts/create_features.py
    deps:
      - Data/adult.data
      - Data/adult.test
      - scripts/create_features.py
    outs:
      - Data/pipeline.pkl
      - Data/processed_train_data.csv
      - Data/processed_test_data.csv
